HolidayProject/urls.py
from django.contrib import admin
from django.urls import path,include
from HotelApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.hotel),
    path('home/',views.home),
    path('newemp/',views.emp),
    path('accounts/',include('django.contrib.auth.urls')),
    path('signup/',views.signup),
    path('upload/',views.upload),
    path('delete/<id>',views.deleteEmp),
    path('update/<id>',views.updateEmp),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HotelApp/models.py
from django.db import models
# Create your models here.

class Employee(models.Model):
    eid=models.IntegerField()
    ename=models.CharField(max_length=30)
    salary=models.FloatField()


class Upload(models.Model):
    name=models.CharField(max_length=50)
    pic=models.FileField(upload_to='images/')
    author=models.CharField(max_length=50)
    uploaddate=models.DateTimeField(auto_now_add=True)

HotelApp/forms.py
from django import forms
from HotelApp.models import Employee,Upload
from django.contrib.auth.models import User
# Create your models here.
class EmployeeForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields='__all__'
        #fields=('eid','ename') ====>tuple
        #exclude=['salary'] #=======>list

class SignupForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email','password')
        widgets = {
            'password': forms.PasswordInput(),
        }

class UploadForm(forms.ModelForm):
    class Meta:
        model=Upload
        fields=('name','pic')



        

HotelApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from HotelApp.models import Employee,Upload
from HotelApp.forms import EmployeeForm,SignupForm,UploadForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def hotel(request):
    dt=datetime.now()
    mydict={"date":dt,"name":"Nitin","email":"ngour@edsystango.com"}
    #return HttpResponse("<h1>Welcome at HotelApp Date:"+str(dt)+" </h1>")
    return render(request,"HotelApp/index.html",context=mydict)

@login_required
def home(request):
    #fetch record from Table  select * from Employee
    emplist=Employee.objects.all()
    mydict={'emplist':emplist}
    print(emplist)
    return render(request,"HotelApp/home.html",context=mydict)

@login_required
def emp(request):
    empform=EmployeeForm()
    mydict={'empform':empform}
    if request.method=='POST':
        empform=EmployeeForm(request.POST)
        empform.save()# insert query
        mydict['msg']='Data Inserted'
    return render(request,"HotelApp/employee.html",context=mydict)

def signup(request):
    sform=SignupForm()
    mydict={'sform':sform}
    if request.method=='POST':
        sform=SignupForm(request.POST)
        user=sform.save() #a a  a admin
        print(user.password,user.first_name)
        user.set_password(user.password)
        user.save()
        mydict['msg']='User Registered Successfylly...'
    return render(request,"HotelApp/signup.html",context=mydict)

@login_required
def upload(request):
    uform=UploadForm()
    mydict={'uform':uform}
    if request.method=='POST':
        uform=UploadForm(request.POST,request.FILES)
        if uform.is_valid():
            data=uform.save(commit=False)
            data.author=request.user
            data.save()
            mydict['msg']='File uploaded Successfylly...'
    images=Upload.objects.all().order_by('-uploaddate')
    mydict['images']=images
    return render(request,"HotelApp/uploadimage.html",context=mydict)

def deleteEmp(request,id):
    e=Employee.objects.get(id=id)
    e.delete()
    emplist=Employee.objects.all()
    mydict={'emplist':emplist,'msg':'Data Deleted'}
    return render(request,"HotelApp/home.html",context=mydict)

def updateEmp(request,id):
    emp=Employee.objects.get(id=id)
    if(request.method=='GET'):
        return render(request,'HotelApp/updateEmpform.html',context={'emp':emp})
    if(request.method=='POST'):
        emp=EmployeeForm(request.POST,instance=emp)
        emp.save()
        emplist=Employee.objects.all()
        mydict={'emplist':emplist,'msg':'Data Updated'}
        return render(request,"HotelApp/home.html",context=mydict)

templates/HotelApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EMS App</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">EMS</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="active"><a href="#">Welcome {{request.user}}</a></li>

      <li><a href="/newemp">Create Employee</a></li>
      <li><a href="/home">View All Employee</a></li>
      <li><a href="/upload">Upload File</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
{%if request.user.is_authenticated is False %}
      <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
{%else%}
      <li><a href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
{%endif%}
    </ul>
  </div>
</nav>

<div class="container">
{%block parent_block%}


{%endblock%}
</div>

</body>
</html>

templates/HotelApp/employee.html
{%extends 'HotelApp/base.html'%}

{%block parent_block%}
{%if msg%}
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>{{msg}}</strong>
</div>
{%endif%}


<h1>Add New Employee Form</h1>

<form  method="POST">
{{empform.as_p}}
{%csrf_token%}
   <input type="submit" value="Save"/>
</form>
{%endblock%}

templates/HotelApp/home.html
{%extends 'HotelApp/base.html'%}

{%block parent_block%}

<h1>Employee Deatials</h1>
{%if msg%}
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>{{msg}}</strong>
</div>
{%endif%}
{%if emplist %}

<table class="table table-hover">
  <tr><th>ID</th><th>EID</th><th>EName</th><th>Salary</th></tr>
 {%for emp in emplist%}
  <tr>
  <td>{{emp.id}}</td>
    <td>{{emp.eid}}</td>
    <td>{{emp.ename}}</td>
    <td>{{emp.salary}}</td>
    <td><a href="/update/{{emp.id}}" class="glyphicon glyphicon-edit" ></a></td>

    <td><a href="/delete/{{emp.id}}" class="glyphicon glyphicon-remove" onclick="return confirm('Do you realy want to delete?')"></a></td>

  </tr>
 {%endfor%}
</table>

{%else%}
<h2>No Data Found...</h2>
{%endif%}
{%endblock%}

templates/HotelApp/index.html
{% extends 'HotelApp/base.html'%}



{%block parent_block%}
<h1>Welcome to EMS</h1>

{%endblock%}

templates/HotelApp/signup.html
{%extends 'HotelApp/base.html'%}

{%block parent_block%}

<h1>New User Registration Form</h1>
{{msg}}

<form method="post">
{{sform.as_p}}
{%csrf_token%}
<input type="submit" value="SignUp" />
</form>

{%endblock%}

templates/HotelApp/updateEmpform.html
{%extends 'HotelApp/base.html'%}

{%block parent_block%}

<h1>Update Employee Deatials</h1>
{%if msg%}
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>{{msg}}</strong>
</div>
{%endif%}

<form  method="POST">
<p><label for="id_eid"></label> <input type="hidden" value={{emp.id}} name="eid" required id="id_eid"></p>
<p><label for="id_eid">Eid:</label> <input type="number" value='{{emp.eid}}' name="eid" required id="id_eid"></p>
<p><label for="id_ename">Ename:</label> <input type="text" value='{{emp.ename}}' name="ename" maxlength="30" required id="id_ename"></p>
<p><label for="id_salary">Salary:</label> <input type="number" value={{emp.salary}} name="salary" step="any" required id="id_salary"></p>
   <input type="submit" value="Update" onclick="return confirm('update???')" />
{%csrf_token%}

</form>
{%endblock%}

templates/HotelApp/uploadimage.html
{%extends 'HotelApp/base.html'%}

{%block parent_block%}
{%if msg%}
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>{{msg}}</strong>
</div>
{%endif%}


<h1>Add New Employee Form</h1>

<form  method="POST" enctype="multipart/form-data">
{{uform.as_p}}
{%csrf_token%}
   <input type="submit" value="Save"/>
</form>


{%if images %}
<table class="table table-hover">
  <tr><th>ID</th><th>File Name</th><th>File</th><th>Author</th><th>Upload Date</th></tr>
 {%for data in images%}
  <tr>
    <td>{{data.id}}</td>
    <td>{{data.name}}</td>
    <td><img src="{{data.pic.url}}" height="50" width="50"/></td>
    <td>{{data.author}}</td>
    <td>{{data.uploaddate | timesince}}</td>
  </tr>
 {%endfor%}
</table>

{%else%}
<h2>No Data Found...</h2>
{%endif%}



{%endblock%}